### ISSUE TITLE
Error when generating an image and using python

### ISSUE THREAD

**Issue by Michspirit99** [boyueluzhipeng/GPT_CodeInterpreter#1]
![image](https://github.com/boyueluzhipeng/GPT_CodeInterpreter/assets/11279621/07700470-5389-47cc-8897-2587520d0731)

When asking to generate an image, i get an error about 'no such file or directory". 
Also when asked to generate a simple python application, and error also occurs: "Invalid syntax, perhaps you forgot a comma?

**Comment by Michspirit99** [comment]
I did not see the code itself suggesting i set the file directory manually. I recommend adding this to the README file so that others don't spin their wheels as well.

For anyone else that sees this:

go to the function manager and and look for /temp. Change the url to a file path of your choice.

**Comment by boyueluzhipeng** [comment]
Thank you for your suggestion, I will adjust and fix it as soon as possible.
